#!/usr/bin/env python3
"""
CoChem-BENCH: ORCA Input Writer
Generates publication-ready ORCA execution input files (.inp) supporting F12, CABS,
Boys-Bernardi Counterpoise, Relativistic Hamiltonians (DKH2/X2C), and parallel allocation.
"""

import logging
from bench_core.basis_manager import map_core_valence_basis_per_element, get_cabs_auxiliary_basis, ATOMIC_NUMBERS

logger = logging.getLogger("CoChem-BENCH.orca_writer")

def generate_dlpno_ccsd_f12(
    coords: list, 
    basis: str = "aug-cc-pVTZ", 
    strategy: str = "INCORE", 
    charge: int = 0, 
    mult: int = 1,
    nprocs: int = 16,
    maxcore_mb: int = 4000,
    is_shift_call: bool = False,
    rel_mode: str = "auto"
) -> str:
    """
    Constructs the complete ORCA input string.
    Supports ZORA, DKH2, and X2C Relativistic Core Potentials / Hamiltonians.
    Restores Grid5 FinalGrid6 high-precision integration grids.
    """
    symbols = [c[0] for c in coords]
    max_z = max(ATOMIC_NUMBERS.get(sym.strip().upper(), 1) for sym in symbols)
    
    # Relativistic core potential resolution (ZORA, DKH2, X2C)
    if rel_mode == "auto":
        is_heavy_relativistic = (max_z > 36)
        active_rel = "DKH2" if is_heavy_relativistic else ""
    elif rel_mode in ["ZORA", "DKH2", "X2C"]:
        is_heavy_relativistic = True
        active_rel = rel_mode
    else:
        is_heavy_relativistic = False
        active_rel = ""

    if active_rel == "ZORA":
        rel_keyword = "ZORA"
    elif active_rel in ["DKH2", "X2C"]:
        rel_keyword = f"Relativistic {active_rel}"
    else:
        rel_keyword = ""

    # Element basis set mapping
    if is_shift_call:
        element_basis_map = map_core_valence_basis_per_element(symbols, base_cv_basis="aug-cc-pCVTZ")
    else:
        element_basis_map = {sym: basis for sym in symbols}

    # CABS space auxiliary basis set
    cabs_basis = get_cabs_auxiliary_basis(basis)

    # Method keyword line with Grid5 FinalGrid6 restored
    method_kw = "DLPNO-CCSD(T)-F12" if strategy == "RIJCOSX_DISK" else "CCSD(T)-F12"
    dft_grid_kw = "Grid5 FinalGrid6"

    # Assemble keyword line
    kw_line = f"! {method_kw} {basis} {cabs_basis} {dft_grid_kw} {rel_keyword}".strip()
    
    # Formulate input file sections
    inp_lines = [
        f"# Generated by CoChem-BENCH for ORCA execution",
        f"{kw_line}",
        "",
        f"%pal nprocs {nprocs} end",
        f"%maxcore {maxcore_mb}",
        ""
    ]

    # Element-specific basis blocks for ZORA / DKH
    if is_shift_call or is_heavy_relativistic:
        inp_lines.append("%basis")
        for sym, b_name in element_basis_map.items():
            if active_rel == "ZORA":
                if not b_name.startswith("ZORA-"):
                    b_name = f"ZORA-{b_name}"
            elif active_rel in ["DKH2", "X2C"]:
                if not b_name.endswith("-DK"):
                    b_name = f"{b_name}-DK"
            inp_lines.append(f'  newgto {sym} "{b_name}" end')
        inp_lines.append("end")
        inp_lines.append("")

    # Coordinate block with charge and multiplicity * xyz {charge} {mult}
    inp_lines.append(f"* xyz {charge} {mult}")
    for item in coords:
        sym, x, y, z = item[0], item[1], item[2], item[3]
        inp_lines.append(f"  {sym:2s}  {x:12.6f}  {y:12.6f}  {z:12.6f}")
    inp_lines.append("*")

    return "\n".join(inp_lines)

def generate_counterpoise_input(
    frag_a_coords: list, 
    frag_b_coords: list, 
    basis: str = "aug-cc-pVTZ", 
    charge: int = 0, 
    mult: int = 1,
    nprocs: int = 16,
    rel_mode: str = "auto"
) -> dict:
    """
    Boys-Bernardi full counterpoise (CP) input generation with Grid5 FinalGrid6 & ZORA/DKH support.
    Generates inputs for Complex (AB), Monomer A with ghost B (A:B), and Monomer B with ghost A (B:A).
    """
    cabs_basis = get_cabs_auxiliary_basis(basis)
    symbols = [c[0] for c in frag_a_coords + frag_b_coords]
    max_z = max(ATOMIC_NUMBERS.get(sym.strip().upper(), 1) for sym in symbols)
    rel_kw = "Relativistic DKH2" if (rel_mode == "auto" and max_z > 36) or rel_mode == "DKH2" else ("ZORA" if rel_mode == "ZORA" else "")
    
    kw_line = f"! DLPNO-CCSD(T)-F12 {basis} {cabs_basis} Grid5 FinalGrid6 {rel_kw}".strip()
    
    def format_coords(coords, ghost_coords):
        lines = [f"%pal nprocs {nprocs} end", "%maxcore 4000", f"* xyz {charge} {mult}"]
        for sym, x, y, z in coords:
            lines.append(f"  {sym:2s}   {x:12.6f}  {y:12.6f}  {z:12.6f}")
        for sym, x, y, z in ghost_coords:
            lines.append(f"  {sym:2s}:  {x:12.6f}  {y:12.6f}  {z:12.6f}")
        lines.append("*")
        return "\n".join([kw_line, ""] + lines)

    complex_input = format_coords(frag_a_coords, frag_b_coords)
    monomer_a_cp = format_coords(frag_a_coords, [(c[0], c[1], c[2], c[3]) for c in frag_b_coords])
    monomer_b_cp = format_coords(frag_b_coords, [(c[0], c[1], c[2], c[3]) for c in frag_a_coords])

    return {
        "complex_input": complex_input,
        "monomer_a_input": monomer_a_cp,
        "monomer_b_input": monomer_b_cp
    }

def compute_counterpoise_corrected_energy(
    e_complex: float,
    e_monomer_a_cp: float,
    e_monomer_b_cp: float,
    e_monomer_a_raw: float = None,
    e_monomer_b_raw: float = None
) -> dict:
    """
    Computes Boys-Bernardi BSSE Counterpoise corrected interaction energy and BSSE error in Hartree and kcal/mol.
    Delta E_CP = E_AB - E_{A:B} - E_{B:A}
    E_BSSE = (E_{A:B} - E_A) + (E_{B:A} - E_B)
    """
    delta_e_cp = e_complex - e_monomer_a_cp - e_monomer_b_cp
    hartree_to_kcal = 627.509474
    
    res = {
        "delta_e_cp_hartree": delta_e_cp,
        "delta_e_cp_kcal": delta_e_cp * hartree_to_kcal
    }
    
    if e_monomer_a_raw is not None and e_monomer_b_raw is not None:
        delta_e_raw = e_complex - e_monomer_a_raw - e_monomer_b_raw
        bsse_a = e_monomer_a_raw - e_monomer_a_cp
        bsse_b = e_monomer_b_raw - e_monomer_b_cp
        e_bsse = bsse_a + bsse_b
        res["delta_e_raw_hartree"] = delta_e_raw
        res["delta_e_raw_kcal"] = delta_e_raw * hartree_to_kcal
        res["e_bsse_hartree"] = e_bsse
        res["e_bsse_kcal"] = e_bsse * hartree_to_kcal

        
    return res

